In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
print("Means: ", df.mean(numeric_only=True))
print("Medians: ", df.median(numeric_only=True))
print("Modes: ", df.mode(numeric_only=True))
print("Standard Deviations: ", df.std(numeric_only=True))
print("Max: ", df.max(numeric_only=True))
print("Min: ", df.min(numeric_only=True))

Means:  Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64
Medians:  Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64
Modes:        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.0           3.0            1.5           0.2
1      2            NaN           NaN            NaN           NaN
2      3            NaN           NaN            NaN           NaN
3      4            NaN           NaN            NaN           NaN
4      5            NaN           NaN            NaN           NaN
..   ...            ...           ...            ...           ...
145  146            NaN           NaN            NaN           NaN
146  147            NaN           NaN            NaN           NaN
147  148            NaN           NaN            NaN           NaN
148  149            NaN           NaN            NaN           NaN
149  150            NaN           NaN            NaN           NaN

[150 rows x 5 columns]
Standard Deviations:  Id               43.445368
SepalLengthCm     0.828066
SepalWidthCm      0.433594
PetalLengthCm     1.764420
PetalWidthCm      0.763161
dtype: float64
Max:  Id               150.0
SepalLengthCm      7.9
SepalWidthCm       4.4
PetalLengthCm      6.9
PetalWidthCm       2.5
dtype: float64
Min:  Id               1.0
SepalLengthCm    4.3
SepalWidthCm     2.0
PetalLengthCm    1.0
PetalWidthCm     0.1
dtype: float64

In [5]:
grouped = df.groupby('Species').mean(numeric_only=True)
print(grouped)

                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5          5.006         3.418          1.464
Iris-versicolor   75.5          5.936         2.770          4.260
Iris-virginica   125.5          6.588         2.974          5.552

                 PetalWidthCm
Species
Iris-setosa             0.244
Iris-versicolor         1.326
Iris-virginica          2.026

In [6]:
df.groupby('Species').describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]